import {profile,education,experience,skills,honors,contact,projects,resumePath} from './data.js';
import {escapeHTML as esc} from './utils.js';
export const chips=items=>`<div class="chips">${items.map(item=>`<span>${esc(item)}</span>`).join('')}</div>`;
export const contactLinks=()=>`<a class="button primary" href="mailto:${contact.email}">Email me ↗</a><a class="button" href="${contact.github}" target="_blank" rel="noopener">GitHub ↗</a>`;
export function aboutHTML(){return `<p>${esc(profile.bio)}</p><p class="muted">${esc(profile.location)}</p><h3>Professional interests</h3>${chips(profile.interests)}`;}
export function educationHTML(){return `<h3>${esc(education.university)}</h3><p>${esc(education.dates)}</p><p>${esc(education.degree)}<br>${esc(education.major)}</p><p>${esc(education.coursework)}<br>${esc(education.campus)}</p>`;}
export function experienceHTML(){return experience.map(item=>`<article class="experience-record"><p class="eyebrow">${esc(item.dates)}</p><h3>${esc(item.title)}</h3><p>${esc(item.role)}<br><span class="muted">${esc(item.organization)}</span></p><ul>${item.work.map(line=>`<li>${esc(line)}</li>`).join('')}</ul>${chips(item.tags)}</article>`).join('');}
export function skillsHTML(){return Object.entries(skills).map(([category,items])=>`<div><h3>${esc(category)}</h3>${chips(items)}</div>`).join('');}
export function honorsHTML(){return `<ul class="honors-list">${honors.map(honor=>`<li>${esc(honor)}</li>`).join('')}</ul>`;}
export function resumeHTML(){return `<p>Education, projects, experience, skills, and honors in one document.</p><div class="actions"><a class="button" data-resume href="${resumePath}" target="_blank" rel="noopener" aria-disabled="true" tabindex="-1">View resume ↗</a><a class="button" data-resume href="${resumePath}" download aria-disabled="true" tabindex="-1">Download PDF ↓</a></div><p class="resume-status muted" role="status">Resume PDF pending. The full portfolio is available in Quick View.</p>`;}
export function projectCards(){return projects.map((p,i)=>`<article class="project-card ${i===0?'featured':''}"><p class="eyebrow">0${i+1} / ${esc(p.type)}</p><h3>${esc(p.title)}</h3><p class="context">${esc(p.context)}${p.role?`<br>${esc(p.role)}`:''}</p><p>${esc(p.description)}</p>${chips(p.technologies)}<button class="text-button" data-open="project" data-id="${p.id}">Read project details ↗</button></article>`).join('');}
export function morrowDemo(){return `<div class="demo"><p class="eyebrow">REPRESENTATIVE PORTFOLIO INTERFACE / SAMPLE DATA</p><h3>Today → Tomorrow</h3><div class="sample-stats"><div>Study time<strong>4h 21m</strong></div><div>Focus sessions<strong>5</strong></div><div>Tasks<strong>6 / 8</strong></div></div><label for="study-hours">Available time <output id="hours-output">3 hours</output></label><input id="study-hours" type="range" min="1" max="6" value="3"><div class="plan"><span>CS 300 <strong id="cs-plan">2h 00m</strong></span><span>Reading <strong id="reading-plan">1h 00m</strong></span></div><p class="demo-note">Fictional sample data and illustrative allocation. This is not the original application or its recommendation algorithm.</p></div>`;}
export function aiDemo(){return `<div class="demo"><p class="eyebrow">ABSTRACT DETECTION / PORTFOLIO SIMULATION</p><div class="detection-scene"><div class="shape shape-a"></div><div class="shape shape-b"></div><div class="shape shape-c"></div><div class="bounding box-a"><span>OBJECT A</span></div><div class="bounding box-b"><span>OBJECT B</span></div><div class="bounding box-c"><span>OBJECT C</span></div><div class="scan-line"></div></div><button class="button" id="detection-toggle" aria-pressed="true">Detection overlay: ON</button><p class="demo-note">Abstract shapes and illustrative bounding boxes. No inference, camera access, or performance claims.</p></div>`;}
export function projectHTML(project){
  const flow=project.id==='morrowlab'?`<h3>Conceptual system flow</h3><div class="architecture"><span>Activity + self-evaluation</span><b>→</b><span>Study context</span><b>→</b><span>Next-day plan</span></div><div class="architecture"><span>Camera</span><b>→</b><span>MediaPipe</span><b>→</b><span>On-device processing</span></div>${morrowDemo()}`:project.id==='detection'?aiDemo():'';
  return `<p class="context">${esc(project.context)}</p>${project.role?`<p class="eyebrow">${esc(project.role)}</p>`:''}<h3>Overview</h3><p>${esc(project.description)}</p>${project.contributions.length?`<h3>My contribution</h3><ul>${project.contributions.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>`:''}<h3>Technology</h3>${chips(project.technologies)}${flow}<div class="actions"><button class="button" data-open="projects">All projects ←</button>${project.repository?`<a class="button" href="${esc(project.repository)}" target="_blank" rel="noopener">Project GitHub ↗</a>`:''}</div>`;
}
